version: '3.4'

services:
  openhab:
    image: "openhab/openhab:2.3.0-amd64-debian"
    restart: always
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "openhab_addons:/openhab/addons"
      - "openhab_conf:/openhab/conf"
      - "openhab_userdata:/openhab/userdata"
      - "/home/openhab/:/tmp/host:ro"
      - "./backups/:/backups"
    environment:
      OPENHAB_HTTP_PORT: "8080"
      OPENHAB_HTTPS_PORT: "8443"
      EXTRA_JAVA_OPTS: "-Duser.timezone=America/Argentina/Buenos_Aires"

  frontail:
    image: "mthenw/frontail:4.2.2"
    restart: always
    ports:
      - "9000:9001"
    volumes:
      - "openhab_userdata:/log:ro"
      - "./frontail_preset.json:/openhab.json:ro"
      - "./frontail_theme.css:/usr/lib/node_modules/frontail/web/assets/styles/openhab.css:ro"  
    command: "--ui-highlight --ui-highlight-preset /openhab.json -t openhab -l 2000 -n 200 /log/logs/openhab.log /log/logs/events.log"

  samba:
    image: "dperson/samba"
    network_mode: "host"
    volumes:
      - "openhab_addons:/openhab_addons"
      - "openhab_conf:/openhab_conf"
      - "openhab_userdata:/openhab_userdata"
      - "./smb.conf:/etc/samba/smb.conf"
    environment:
      - "NMBD=true"
      - "TZ=${DOCKER_TZ}"
      - "RECYCLE=False"
      - "USER=openhab;openhab"
    restart: always

  mosquitto:
    image: "eclipse-mosquitto:1.4.12"
    volumes:
      - "./mosquitto/:/mosquitto/config/"
      - "./mosquitto_passwd:/etc/mosquitto/passwd"
    ports:
      - "9001:9001"
      - "1883:1883"
    restart: always

  grafana:
    image: "grafana/grafana:5.1.0"
    ports:
      - "3000:3000"
    environment:
      - "GF_SERVER_ROOT_URL=http://openhab_master.lan"
      - "GF_SECURITY_ADMIN_PASSWORD=admin"
      - "GF_AUTH_ANONYMOUS_ENABLED=true"
    volumes:
      - "grafana-storage:/var/lib/grafana"

  influxdb:
    image: "influxdb:1.6"
    ports:
      - "8086:8086"
    volumes:
      - "influxdb-storage:/var/lib/influxdb"
    environment:
      - "INFLUXDB_DB=openhab_db"
      - "INFLUXDB_USER=openhab"
      - "INFLUXDB_USER_PASSWORD=openhab"


volumes:
  openhab_addons:
    driver: local
  openhab_conf:
    driver: local
  openhab_userdata:
    driver: local
  grafana-storage:
    driver: local
  influxdb-storage:
    driver: local
