version: '3.4'

services:
  openhab:
    image: "openhab/openhab:2.3.0-amd64-debian"
    restart: always
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "openhab_addons:/openhab/addons"
      - "openhab_conf:/openhab/conf"
      - "openhab_userdata:/openhab/userdata"
      - "/home/openhab/:/tmp/host:ro"
    environment:
      OPENHAB_HTTP_PORT: "8080"
      OPENHAB_HTTPS_PORT: "8443"
      EXTRA_JAVA_OPTS: "-Duser.timezone=America/Argentina/Buenos_Aires"

  frontail:
    image: "mthenw/frontail"
    restart: always
    ports:
      - "9001:9001"
    volumes:
      - "openhab_userdata:/log:ro"
      - "./frontail_preset.json:/openhab.json:ro"
      - "./frontail_theme.css:/usr/lib/node_modules/frontail/web/assets/styles/openhab.css:ro"  
    command: "--ui-highlight --ui-highlight-preset /openhab.json -t openhab -l 2000 -n 200 /log/logs/openhab.log /log/logs/events.log"

  samba:
    image: "dperson/samba"
    network_mode: "host"
    volumes:
      - "openhab_addons:/openhab_addons"
      - "openhab_conf:/openhab_conf"
      - "openhab_userdata:/openhab_userdata"
      - "./smb.conf:/etc/samba/smb.conf"
    environment:
      - "NMBD=true"
      - "TZ=${DOCKER_TZ}"
      - "RECYCLE=False"
    restart: always

volumes:
  openhab_addons:
    driver: local
  openhab_conf:
    driver: local
  openhab_userdata:
    driver: local

